### ISSUE TITLE
`given JsonValueCodec[Option[String]] = JsonCodecMaker.make[Option[String]]` fails compilation

### ISSUE THREAD

**Issue by lolgab** [plokhotnyuk/jsoniter-scala#995] opened 2023-02-18 10:43 UTC
The following code:
```scala
given JsonValueCodec[Option[String]] = JsonCodecMaker.make[Option[String]]
```

Returns the following error:
```
-- Error: MyFile.scala:7:58 
  7 |given JsonValueCodec[Option[String]] = JsonCodecMaker.make[Option[String]]
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                   Exception occurred while executing macro expansion.
    |                   java.lang.Exception: Expr cast exception: null
    |                   of type: scala.Null
    |                   did not conform to type: java.lang.String
    |
    |
    |---------------------------------------------------------------------------
    |Inline stack trace
    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |This location contains code that was inlined from JsonCodecMaker.scala:500
     -------------------------------------------------------------------------------
```

**EDIT**
This happens only in Scala 3 when using the `-Yexplicit-nulls` compiler option which is not supported at the moment: https://github.com/plokhotnyuk/jsoniter-scala/issues/988

**Comment by plokhotnyuk** [comment] 2023-02-18 17:10
Hi, Lorenzo!

Thanks for reporting, but I cannot reproduce the issue locally using the following unit test:
```scala
    "don't generate codecs for option string" in {
      assert(intercept[TestFailedException](assertCompiles {
        "given JsonValueCodec[Option[String]] = JsonCodecMaker.make[Option[String]]"
      }).getMessage.contains {
        "exception"
      })
    }
```

Could you please share the project or list concrete steps how to reproduce it.

**Comment by lolgab** [comment] 2023-02-19 10:53
Sorry @plokhotnyuk, I tried to reproduce and I couldn't either..
Then I understood why. It's because I use `-Yexplicit-nulls` which is not supported by jsoniter-scala https://github.com/plokhotnyuk/jsoniter-scala/issues/988
So this is a duplicate of that issue!

Trying to reproduce I found another compilation issue with:
```
import com.github.plokhotnyuk.jsoniter_scala.macros._
import com.github.plokhotnyuk.jsoniter_scala.core._

val foo = JsonCodecMaker.make[Some[String]]
```
Which gives:
```
[error] -- Error: /Users/lorenzo/scala/example-mill-4/module/src/Main.scala:4:29 -------
[error]   4 |val foo = JsonCodecMaker.make[Some[String]]
[error]     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |          Exception occurred while executing macro expansion.
[error]     |          java.lang.Exception: Expr cast exception: scala.None
[error]     |          of type: scala.None
[error]     |          did not conform to type: scala.Some[scala.Predef.String]
[error]     |
[error]     |
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from JsonCodecMaker.scala:500
[error]      ---------------------------------------------------------------------------

```

**Comment by plokhotnyuk** [comment] 2023-02-19 13:37
@lolgab Thanks for clarifying!

I'm closing this issue as duplicated. Please vote for https://github.com/plokhotnyuk/jsoniter-scala/issues/988 if you going to use jsoniter-scala with `-Yexplicit-nulls`.

**Closed by plokhotnyuk** 2023-02-19 13:37 UTC
